import os
'''
Experiment lake name list
'''

def lake_list():
    '''
    Names of the lakes used in the objective function
    '''
    llist={
        S0a: ['none'],
        S0b: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Loontail_122',
                'Misty_135',
                'Narrowbag_281',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1a: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Loontail_122',
                'Misty_135',
                'Narrowbag_281',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1b: [  'Narrowbag_281',
                'Grand_753',
                'Radiant_574',
                'Misty_135',
                'Traverse_767',
                'Big_Trout_220'],
        S1c: ['none'],
        S1d: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Loontail_122',
                'Misty_135',
                'Narrowbag_281',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1e: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1f: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Loontail_122',
                'Misty_135',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1g: [  'Burntroot_228',
                'Narrowbag_281',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',],
        S1h: [  'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Little_Cauchon_449',
                'Misty_135',
                'Narrowbag_281',
                'North_Depot_497',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1i: [  'Animoosh_345',
                'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Hogan_291',
                'La_Muir_241',
                'Little_Cauchon_449',
                'Narrowbag_281',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1j: [  'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Little_Cauchon_449',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
        S1k: [  'Big_Trout_220',
                'Burntroot_228',
                'Cedar_528',
                'Grand_753',
                'Little_Cauchon_449',
                'Narrowbag_281',
                'Radiant_574',
                'Traverse_767',
                'Lavieille_326'],
    }